# Generated by Django 3.1.7 on 2021-02-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0002_imported_csvs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
