# Generated by Django 3.1.7 on 2021-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0003_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='imported_csvs',
            name='Measurement_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imported_csvs',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imported_csvs',
            name='Measurement_1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
