# Generated by Django 3.1.7 on 2021-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=64, null='False')),
                ('files', models.FileField(upload_to='media')),
            ],
        ),
    ]
